name: actions
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'building'

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: staging
    env:
      TEST_2: ${{ secrets.TESTING }}
    steps:
      - name: publish
        run: echo 'publishing'
      - run: echo "secrets.TESTING ${{ secrets.TESTING }}"
      - run: echo "env TEST_2 ${{ env.TESTING }}"
