name: actions
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'building'

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: echo 'publishing'
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env
